---
    version: '3.7'
    services:
      service1:
        image: bwdaniels97/service1:latest
        build: ./service1 
        ports:
        - target: 5000
          published: 5000
          protocol: tcp
        deploy:
          replicas: 2
        environment:
          SECRET_KEY: ${SECRET_KEY}
          DATABASE_URI: ${DATABASE_URI}
         
        
      service2:
        image: bwdaniels97/service2:latest      
        build: ./service2
        ports:
        - target: 5001
          published: 5001
          protocol: tcp
        deploy:
          replicas: 2  
      service3:
        image: bwdaniels97/service3:latest
        build: ./service3
        ports:
        - target: 5002
          published: 5002
          protocol: tcp
        deploy:
          replicas: 2  
      service4:
        image: bwdaniels97/service4:latest      
        build: ./service4
        ports:
        - target: 5003
          published: 5003
          protocol: tcp
        deploy:
          replicas: 2  
    
...   
