- name: 'update apt and install packages'
  apt:
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - python3-pip  
    state: latest
    update_cache: true

- name: 'add GPG key'
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: "make a repository"
  apt_repository:
          repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
          state: present

- name: 'install docker'
  apt:
    pkg:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    state: latest


- name: "add user to the docker group"
  user:
        name: "bwdaniels97"
        group: docker
        state: present
